# Generated by Django 5.2.5 on 2025-08-07 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Academic', 'Academic'), ('Hostel', 'Hostel'), ('Mess', 'Mess'), ('Transport', 'Transport'), ('Library', 'Library'), ('Examination', 'Examination'), ('WiFi/Internet', 'WiFi/Internet'), ('Classroom Infrastructure', 'Classroom Infrastructure'), ('Sanitation', 'Sanitation'), ('Faculty', 'Faculty'), ('Fees/Billing', 'Fees/Billing'), ('Security', 'Security'), ('Ragging/Harassment', 'Ragging/Harassment'), ('Lab Equipment', 'Lab Equipment'), ('Canteen', 'Canteen'), ('Event Management', 'Event Management'), ('Sports/Gym', 'Sports/Gym'), ('Medical/Health', 'Medical/Health'), ('Scholarship', 'Scholarship'), ('Placement/Training', 'Placement/Training'), ('Others', 'Others')], max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')])),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grienvances.complaints')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='grienvances.complaints')),
            ],
        ),
    ]
