# Generated by Django 5.2.5 on 2025-09-08 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grienvances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Academic', 'Academic'), ('Hostel', 'Hostel'), ('Mess', 'Mess'), ('Transport', 'Transport'), ('Library', 'Library'), ('Examination', 'Examination'), ('WiFi/Internet', 'WiFi/Internet'), ('Classroom Infrastructure', 'Classroom Infrastructure'), ('Sanitation', 'Sanitation'), ('Faculty', 'Faculty'), ('Fees/Billing', 'Fees/Billing'), ('Security', 'Security'), ('Ragging/Harassment', 'Ragging/Harassment'), ('Lab Equipment', 'Lab Equipment'), ('Canteen', 'Canteen'), ('Event Management', 'Event Management'), ('Sports/Gym', 'Sports/Gym'), ('Medical/Health', 'Medical/Health'), ('Scholarship', 'Scholarship'), ('Placement/Training', 'Placement/Training'), ('Others', 'Others')], max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=50)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High')], default='Normal', max_length=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='complaint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='grienvances.complaint'),
        ),
        migrations.AlterField(
            model_name='response',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='grienvances.complaint'),
        ),
        migrations.DeleteModel(
            name='Complaints',
        ),
    ]
