# Generated by Django 5.1.7 on 2025-09-08 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grienvances', '0003_rename_submitted_at_feedback_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(blank=True, choices=[('Academic', 'Academic'), ('Hostel', 'Hostel'), ('Mess', 'Mess'), ('Transport', 'Transport'), ('Library', 'Library'), ('Examination', 'Examination'), ('WiFi/Internet', 'WiFi/Internet'), ('Classroom Infrastructure', 'Classroom Infrastructure'), ('Sanitation', 'Sanitation'), ('Faculty', 'Faculty'), ('Fees/Billing', 'Fees/Billing'), ('Security', 'Security'), ('Ragging/Harassment', 'Ragging/Harassment'), ('Lab Equipment', 'Lab Equipment'), ('Canteen', 'Canteen'), ('Event Management', 'Event Management'), ('Sports/Gym', 'Sports/Gym'), ('Medical/Health', 'Medical/Health'), ('Scholarship', 'Scholarship'), ('Placement/Training', 'Placement/Training'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
